title: Ivan Ramos # your name (or website title) here
logo: "/images/63434710.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My interest in embedded software started pretty late into my college career when I was 
  asigned the role of ebeded developer at a reserach project. I quickly fell in love with 
  the idea of working with hardware and software and writing software with hardware in mind.
  Since then I have messed with multiple embedded platforms and explored other areas such as
  robotics and Linux kernel developments.
  <br><br>
  While my formal education is in electrical engineering, you will find from my projects
  that I have a deep interest in software. More specifically embedded software. I hope
  to find a role that will allow me continue to explore my interests while contributing
  with all of my past expereiences.
  <br><br>
  <a href="https://www.linkedin.com/in/ivan-ramos-05503a134/">View My LinkedIn Profile</a> 
  <a href="https://github.com/vergi1iu5">View My GitHub</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
